
name: wms-prod

services:
  db:
    image: postgres:16
    container_name: wms_prod_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        APP_VERSION: ${APP_VERSION:-}
    container_name: wms_prod_backend
    restart: always
    environment:
      APP_ENV: prod
      APP_VERSION: ${APP_VERSION:-}
    env_file:
      - .env.prod
    depends_on:
      - db
    ports:
      - "127.0.0.1:10000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_TITLE: "pack-men - prod"
    container_name: wms_prod_frontend
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - backend
    ports:
      - "127.0.0.1:10080:80"

volumes:
  db_data:
