name: wms

services:
  db:
    image: postgres:16
    container_name: wms_postgres
    restart: always
    environment:
      POSTGRES_USER: proforyou
      POSTGRES_PASSWORD: 1qaz#EDC
      POSTGRES_DB: wms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: