export const OP_LABELS: Record<string, string> = {
  doc_create: 'Рейс создан',
  doc_update: 'Рейс изменён',
  receipt_link: 'Привязано поступление',
  receipt_unlink: 'Отвязано поступление',
  shipment_link: 'Привязана отгрузка',
  shipment_unlink: 'Отвязана отгрузка',
  handoff: 'Передан на склад',
  arrival: 'Прибытие машины',
  departure: 'Прибытие машины',
  unload_done: 'Разгрузка завершена',
  load_done: 'Погрузка завершена',
  cost_actual: 'Внесена стоимость',
  close: 'Рейс закрыт',
  cancel: 'Рейс аннулирован',
}

export const OP_ICONS: Record<string, string> = {
  doc_create: 'plus',
  doc_update: 'edit',
  receipt_link: 'plus',
  receipt_unlink: 'minus',
  shipment_link: 'plus',
  shipment_unlink: 'minus',
  handoff: 'arrowRight',
  arrival: 'truckIn',
  departure: 'truckIn',
  unload_done: 'forklift',
  load_done: 'forklift',
  cost_actual: 'ruble',
  close: 'check',
  cancel: 'x',
}

export const OP_TONES: Record<string, string> = {
  doc_create: 'accent',
  doc_update: '',
  receipt_link: 'info',
  receipt_unlink: 'warning',
  shipment_link: 'info',
  shipment_unlink: 'warning',
  handoff: 'accent',
  arrival: 'info',
  departure: 'info',
  unload_done: 'success',
  load_done: 'success',
  cost_actual: 'accent',
  close: 'success',
  cancel: 'danger',
}
