script: |
  cd /var/www/app-prod

  printf "DATABASE_URL=%s\nVITE_API_BASE_URL=%s\n" \
    "${{ secrets.DATABASE_URL }}" \
    "${{ secrets.VITE_API_BASE_URL }}" > .env.prod

  docker compose -f docker-compose.prod.yml up -d --build